### NETWORKS ###
networks:
    proxy:
        external: true

### Services ###
services:
    nginx-mailcow:
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.moo-rtr.entrypoints=https,http"
            - "traefik.http.routers.moo-rtr.rule=Host(`${MAILCOW_HOSTNAME}`)"
            - "traefik.http.routers.moo-rtr.tls=true"
            - "traefik.http.routers.moo-rtr.service=moo-svc"
            - "traefik.http.services.moo-svc.loadbalancer.server.port=7083"
#            - "traefik.http.routers.moo-rtr.middlewares=chain-no-auth@file"

    certdumper:
        image: humenius/traefik-certs-dumper
        container_name: traefik_certdumper
        network_mode: none
        volumes:
            - ../traefik/volume/:/traefik:ro
            - ./data/assets/ssl/:/output:rw
        environment:
            - DOMAIN=${MAILCOW_HOSTNAME}