services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_URL=https://${SUB_DOMAIN}.${DOMAIN}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DB_PASSWD}
      - DB_DATABASE=bookstackapp
    volumes:
      - ./volume/app_data:/config
#    ports:
#      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      proxy:
      bookstack:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUB_DOMAIN}.entrypoints=http"
      - "traefik.http.routers.${SUB_DOMAIN}.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.middlewares.${SUB_DOMAIN}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SUB_DOMAIN}.middlewares=${SUB_DOMAIN}-https-redirect"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.entrypoints=https"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls=true"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.service=${SUB_DOMAIN}"
      - "traefik.http.services.${SUB_DOMAIN}.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DB_PASSWD}
    volumes:
      - ./volume/db:/config
    restart: unless-stopped
    networks:
      bookstack:

networks:
  proxy:
    external: true
  bookstack: