services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
     - GF_SERVER_ROOT_URL=https://${SUB_DOMAIN}.${DOMAIN}/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
#    ports:
#     - '3000:3000'
    volumes:
     - './volume:/var/lib/grafana'
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUB_DOMAIN}.entrypoints=http"
      - "traefik.http.routers.${SUB_DOMAIN}.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.middlewares.${SUB_DOMAIN}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SUB_DOMAIN}.middlewares=${SUB_DOMAIN}-https-redirect"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.entrypoints=https"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls=true"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.service=${SUB_DOMAIN}"
      - "traefik.http.services.${SUB_DOMAIN}.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true