---

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /home/silas/vol/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /home/silas/vol/nextcloud/html:/var/www/html
      - /home/silas/vol/nextcloud/php.ini:/usr/local/etc/php/conf.d/nextcloud.ini #create php.ini on host
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - TRUSTED_DOMAINS=mydataspace.net
      - TRUSTED_PROXIES=192.168.2.199
      - OVERWRITEHOST=mydataspace.net
      - OVERWRITEPROTOCOL=https  
      - DEFAULT_LANGUAGE=en
      - DEFAULT_LOCALE=de_DE
      - DEFAULT_PHONE_REGION=DE