services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

#    ports:
#      - 3000:3000
    volumes:
      - ./volume/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - ./volume/imgs:/app/public/images
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUB_DOMAIN}.entrypoints=http"
      - "traefik.http.routers.${SUB_DOMAIN}.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.middlewares.${SUB_DOMAIN}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SUB_DOMAIN}.middlewares=${SUB_DOMAIN}-https-redirect"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.entrypoints=https"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls=true"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.service=${SUB_DOMAIN}"
      - "traefik.http.services.${SUB_DOMAIN}.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true